#!/usr/bin/env node
/**
 * Compile the console UI into a TypeScript module of string literals.
 *
 * The surveyed projects all ship their SPA as files and serve them off
 * disk — bull-board resolves its UI package's directory at runtime with
 * `eval("require.resolve(...)")` to survive bundlers, River UI had to build
 * a bespoke Go module proxy to vendor its `dist/`. We do neither: the built
 * JS and CSS become string constants that tsup bundles into `dist/`, so the
 * handler needs no filesystem at all and therefore runs unchanged on
 * Workers, Deno and every other runtime without `fs` — which matters,
 * because the engine ships a serverless host.
 *
 * Asset names carry a content hash so they can be served `immutable`.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const outDir = join(pkg, "src", "generated");

const bundle = await esbuild.build({
  entryPoints: [join(pkg, "ui", "app.tsx")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2022"],
  jsx: "automatic",
  jsxImportSource: "preact",
  outfile: "app.js",
  write: false,
  legalComments: "none",
  logLevel: "warning",
});

const js = bundle.outputFiles.find((file) => file.path.endsWith(".js"));
if (!js) throw new Error("build-ui: esbuild produced no JS output");

const css = readFileSync(join(pkg, "ui", "styles.css"), "utf8");
// The stylesheet is small and hand-written, so it only needs whitespace
// squeezed out; running it through esbuild's CSS pipeline would buy nothing.
const cssMin = css
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/\s*([{}:;,>])\s*/g, "$1")
  .replace(/;}/g, "}")
  .replace(/\s+/g, " ")
  .trim();

const jsText = js.text;
const hash = (text) => createHash("sha256").update(text).digest("hex").slice(0, 10);

const jsName = `app.${hash(jsText)}.js`;
const cssName = `app.${hash(cssMin)}.css`;

mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "ui-bundle.ts"),
  `// GENERATED by scripts/build-ui.mjs — do not edit, do not commit.
export const UI_JS_NAME = ${JSON.stringify(jsName)};
export const UI_CSS_NAME = ${JSON.stringify(cssName)};
export const UI_JS = ${JSON.stringify(jsText)};
export const UI_CSS = ${JSON.stringify(cssMin)};
`,
  "utf8",
);

const kb = (text) => (Buffer.byteLength(text, "utf8") / 1024).toFixed(1);
console.log(
  `build-ui: ${jsName} ${kb(jsText)} kB, ${cssName} ${kb(cssMin)} kB`,
);
